# States
states = [
    "Andaman and Nicobar Islands",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadra and Nagar Haveli",
    "Daman and Diu",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Pondicherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal"
]

# States - Cities Mapping
cities = {'Andaman and Nicobar Islands': ['Port blair'],
 'Andhra Pradesh': ['Anakapalle',
                    'Proddatur',
                    'Visakhapatnam',
                    'Chittoor',
                    'Naamavaram',
                    'Jaggaiahpet',
                    'Ongole',
                    'Gudur',
                    'Kalavapalli',
                    'Eluru',
                    'Jangareddygudem',
                    'Arasada',
                    'Jaggampeta',
                    'Sullurupeta',
                    'Gadanki',
                    'Vijayawada',
                    'Anantapuram',
                    'Dachepalli',
                    'Vizianagaram',
                    'Chilakaluripet',
                    'Guntur',
                    'Krishna',
                    'Perecherla',
                    'Jagannadhapuram',
                    'Vempadu',
                    'Gudavalli',
                    'Bhimavaram',
                    'Tada',
                    'Ramachandrapuram',
                    'Tadepalligudem',
                    'Patiala',
                    'Rajamahendravaram',
                    'Ooty',
                    'Chimalapadu',
                    'Komirepalle',
                    'Alampuram',
                    'Santhanuthalapadu',
                    'Tallapalem',
                    'Kurnool',
                    'Nandigama',
                    'Kaikaluru',
                    'Potti sriramulu ne',
                    'Prathipadu',
                    'Srikakulam',
                    'Nellore',
                    'Gannavaram',
                    'Kadapa',
                    'Vuyyuru',
                    'Konduru',
                    'Tirupati'],
 'Assam': ['Guwahati', 'Jorhat', 'Nagaon'],
 'Bihar': ['Hatna', 'Bhagalpur', 'Danapur', 'Gaya', 'Nalanda'],
 'Chandigarh': ['Chandigarh'],
 'Chhattisgarh': ['Khursipar', 'Bhilai', 'Jabalpur', 'Bilaspur', 'Jaipur'],
 'Delhi': ['Delhi',
           'Mayapuri',
           'South east',
           'Rohini',
           'Newdelhi',
           'Connaught place',
           'Gurugram',
           'Patparkang'],
 'Goa': ['Taleigao', 'Penha de frança,', 'Candolim', 'Goa'],
 'Gujarat': ['Malda',
             'Surat',
             'Changodar',
             'Rajkot',
             'Kevadia',
             'Botad',
             'Dabhoi',
             'Kosamba',
             'Morbi',
             'Anand',
             'Sundarnagar',
             'Bharuch',
             'Ahmedabad',
             'Kamod',
             'Vadodara',
             'Amboli',
             'Bhavnagar',
             'Mahesana',
             'Karjan',
             'Vapi',
             'Valsad',
             'Bhuj',
             'Limbdi',
             'Dwarka',
             'Dhrangadhra',
             'Junagadh',
             'Gandhinagar',
             'Mundra',
             'Gandhidham'],
 'Haryana': ['Hisar',
             'Rewari',
             'Karnal',
             'Shahbad',
             'Faridabad',
             'Panchgani',
             'Ambala city',
             'Malikpura',
             'Ucchana',
             'Sonipat',
             'Palwal',
             'Sangli',
             'Mahendragarh',
             'Sirsa',
             'Ganaur',
             'Gurgaon'],
 'Himachal Pradesh': ['Barog',
                      'Sirmaur',
                      'Shimla',
                      'Sundarnagar',
                      'Kasauli',
                      'Dharamshala',
                      'Una',
                      'Dohand'],
 'Hyderabad': ['Hyderabad'],
 'Jammu and Kashmir': ['Greater noida',
                       'Ghagwal',
                       'Karad',
                       'Ramban',
                       'Srinagar',
                       'Udhampur',
                       'Kathua nh',
                       'Sangamner',
                       'Jhajjar kotli',
                       'Nagrota',
                       'Jammu'],
 'Jharkhand': ['Ranchi', 'Bokaro', 'Dhanbad', 'Jamshedpur'],
 'Karnataka': ['Bantwal',
               'Kolar',
               'Koppa',
               'Hiriyur',
               'Chitradurga',
               'Kabini colony',
               'Hassan',
               'Karkala',
               'Kundra',
               'Udupi',
               'Hatna',
               'Madikeri',
               'Bengaluru',
               'Gonikappa',
               'Hubli',
               'Kushalnagar',
               'Nidaghatta',
               'Bhadravati',
               'Dakshina kannada',
               'Chikmagalur',
               'Shanthigrama',
               'Vijayapura',
               'Mudigere',
               'Tumkur',
               'Belgaum',
               'Mudbidri',
               'Davangere',
               'Sakleshpur',
               'Manipal',
               'Sirsa',
               'Chennapatna',
               'Basavakalyan',
               'Virarajendrapet',
               'Mysuru',
               'Mangaluru',
               'Puttur',
               'Mandya',
               'Yediyur',
               'Shimoga',
               'Coorg'],
 'Kerala': ['Idukki',
            'Nilambur',
            'Vadakkancherry',
            'Velimukku',
            'North paravur',
            'Kasargode',
            'Trissur',
            'Walayar',
            'Waynad',
            'Kundra',
            'Edappla',
            'Kuttikkanam',
            'Thalassery',
            'Manoor',
            'Aleppey',
            'Kottayam',
            'Kizhakkummuri',
            'Pattikkad',
            'Kalpetta',
            'Aluva',
            'Mararikulam',
            'Munnar',
            'Nhangattiri',
            'Alappuzha',
            'Guruvayur',
            'Engandiyoor',
            'Thiruvananthapuram',
            'Mundakayam',
            'Periyar',
            'Pathanapuram',
            'Vadanappally',
            'Perintalmanna',
            'Malappuram',
            'Kumily',
            'Nedumkunnam',
            'Pathanamthitta',
            'Perumbavoor',
            'Adoor',
            'Kannur',
            'Valanchery',
            'Madiyoorkuni',
            'Kollam',
            'Kochi',
            'Pattambi',
            'Angamali',
            'Mahe',
            'Nadal',
            'Kottakkal',
            'Palakkad',
            'Latur',
            'Kozhikode',
            'Kunnakulam',
            'Neyyattinkara',
            'Vettichira',
            'Ernakulam',
            'Changanassery'],
 'Madhya Pradesh': ['Chhindwara',
                    'Rewari',
                    'Bhopal',
                    'Mocha',
                    'Sagar',
                    'Indore',
                    'Ujjain',
                    'Jabalpur',
                    'Chhatarpur',
                    'Rajgad-bhopal'],
 'Maharashtra': ['Amravati',
                 'Pimpri-chinchwad',
                 'Karad',
                 'Beed',
                 'Indapur',
                 'Miraj',
                 'Aurangabad',
                 'Ghoti',
                 'Bhandara',
                 'Haji ali jn, thack',
                 'Shirdi',
                 'Vasai',
                 'Nashik',
                 'Pune',
                 'Eluru',
                 'Valane',
                 'Kangoni',
                 'Dhawalpeth',
                 'Satara',
                 'Tal-bhivandi',
                 'Bhiwadi',
                 'Gonde',
                 'Karanja ghadge',
                 'Ahmednagar',
                 'Dhule',
                 'Ajara',
                 'Vadavli',
                 'Butibori',
                 'Mahad',
                 'Tekadi',
                 'Chhatarpur',
                 'Malkhed',
                 'Baramati',
                 'Panvel',
                 'Uruli kanchan',
                 'Washim',
                 'Sajgaon',
                 'Gurgaon',
                 'Oglapur',
                 'Pandharpur',
                 'Asangoan',
                 'Thane',
                 'Savalivihir',
                 'Kalyan',
                 'Shedung',
                 'Khopoli',
                 'Sawantwadi',
                 'Mahableshwar',
                 'Palghar',
                 'Ridhora',
                 'Raigad',
                 'Kurkumbh',
                 'Deori',
                 'Lonavala',
                 'Wardha',
                 'Panchgani',
                 'Nagewadi',
                 'Sinnar taluka',
                 'Demni shekta',
                 'Shiroli',
                 'Latur',
                 'Mumbai',
                 'Nagaur',
                 'Sangamner',
                 'Khed',
                 'Wadoda',
                 'Ganpatiphule',
                 'Talegaon dabhade',
                 'Chouk'],
 'Manipur': ['Imphal'],
 'Odisha': ['Kalahandi',
            'Keonjhar',
            'Bhubaneswar',
            'Cuttack',
            'Berhampur',
            'Tentulipada',
            'Angul',
            'Kalinganagar',
            'Jeypore',
            'Jabalpur',
            'Puri',
            'Balasore',
            'Urali',
            'Jaipur'],
 'Pondicherry': ['Pondicherry'],
 'Puducherry': ['Puducherry'],
 'Punjab': ['Phagwara',
            'Mukerian',
            'Dhar kalan',
            'Kisangarh',
            'Sas nagar',
            'Bharatgarh',
            'Zirakpur',
            'Jalandhar',
            'Madhopur',
            'Kaddon',
            'Amritsar',
            'Dhaki saidan',
            'Sangrur',
            'Sahnewal',
            'Phillaur',
            'Pathankot',
            'Ludhiana',
            'Shambhu',
            'Patiala',
            'Dera bassi',
            'Punjab',
            'Mohali'],
 'Rajasthan': ['Beawar',
               'Sayri',
               'Bharatpur',
               'Nathdwara',
               'Kisangarh',
               'Ajmer',
               'Pushkar',
               'Jhunjhunu',
               'Dausa',
               'Bhiwadi',
               'Barapal',
               'Alwar',
               'Kota',
               'Chittorgarh',
               'Madhopur',
               'Jodhpur city',
               'Sirohi',
               'Bahror',
               'Bhilwara',
               'Sikar',
               'Rajsamand',
               'Shahpura',
               'Jaisalmer',
               'Salasar',
               'Udaipur',
               'Sri ganganagar',
               'Shahjahanpur, rj',
               'Beesalpur',
               'Deograh',
               'Nagaur',
               'Pali',
               'Jaipur'],
 'Sikkim': ['Pakyong', 'Gangtok'],
 'Tamil Nadu': ['Perundurai',
                'Ulundurpet',
                'Villupuram',
                'Thindivanam',
                'Velankannai',
                'Avinashi',
                'Chidambaram',
                'Sriperumbudur',
                'Tiruchirapalli',
                'Salem',
                'Rasipuram',
                'Kanyakumari',
                'Tiruvannamalai',
                'Yelagiri',
                'Aarani',
                'Virudhunagar',
                'Mahabalipuram',
                'Sas nagar',
                'Pallikonda',
                'Kanchipuram',
                'Eluru',
                'Namakkal',
                'Tiruppur',
                'Yercaud',
                'Madurai',
                'Thirumangalam',
                'Sankari',
                'Kumbakonam',
                'Trichy',
                'Mettupalayam',
                'Sannamangalam',
                'Irungattukottai',
                'Vikravandi',
                'Chengalpattu',
                'Coimbatore',
                'Tiruttani',
                'Attur',
                'Dharmapuri',
                'Krishnagiri',
                'Sirkali',
                'Sengalikuppam',
                'Dindigul',
                'Palyampudur',
                'Kodaikanal',
                'Kodikulam',
                'Melmaruvathur',
                'Ooty',
                'Thiruvanmiyur',
                'Viralimalai',
                'Ambur',
                'Hosur',
                'Chengampalli',
                'Omalur',
                'Shoolagiri',
                'Gundalapalli villa',
                'Perambalur',
                'Karur',
                'Nellore',
                'Chennai',
                'Vadippatti',
                'Tirunelveli',
                'Pali',
                'Chinnavalavanur',
                'Tirupati'],
 'Telangana': ['Telangana',
               'Aswapuram',
               'Kamareddy',
               'Thippapuram',
               'Mahabubnagar',
               'Medchal-malkajgiri',
               'Rangareddy',
               'Ramagundam',
               'Suryapet',
               'Kodad',
               'Tekulpally',
               'Banswada',
               'Moosapet',
               'Nalogonda',
               'Elkathurthy',
               'Siddipet',
               'Narketpalle',
               'Khammam',
               'Nizamabad',
               'Bhadrachalam',
               'Bhongir',
               'Oglapur',
               'Parkal',
               'Varni',
               'Jedcharla',
               'Jogipet',
               'Madgulapally',
               'Yadadri bhuvanagir',
               'Bikroor',
               'Nirmal',
               'Zahirabad',
               'Karimnagar',
               'Venkatapuram',
               'Paloncha',
               'Peddapalli',
               'Adilabad',
               'Warangal',
               'Sathupalli',
               'Bhuvanagiri'],
 'Tripura': ['Agartala'],
 'Uttar Pradesh': ['Dhar kalan',
                   'Mathura',
                   'Bareilly',
                   'Sultanpur',
                   'Varanasi',
                   'Moradabad',
                   'Ghaziabad',
                   'Kasauli',
                   'Agra',
                   'Mansurpur',
                   'Noida',
                   'Lucknow',
                   'Greater noida',
                   'Saharanpur',
                   'Muzaffarnagar',
                   'Bagahi - kumbhapur',
                   'Mainpuri',
                   'Aligarh',
                   'Gajraula',
                   'Meerut',
                   'Kannur',
                   'Gorakhpur',
                   'Ekdil',
                   'Bhainsi',
                   'Shahjahanpur, rj',
                   'Ayodhya'],
 'Uttarakhand': ['Nainital',
                 'Haldwani',
                 'Dehradun',
                 'Udaipur',
                 'Rishikesh',
                 'Jamnagar',
                 'Haridwar'],
 'West Bengal': ['Malda',
                 'Hubli',
                 'Kharagpur',
                 'Nadal',
                 'Bardhaman',
                 'Bayamari',
                 'Rupnarayanpur',
                 'Kolkata',
                 'Raiganj',
                 'Durgapur',
                 'Digha',
                 'Coochbehar',
                 'Birbhum',
                 'Howrah',
                 'Kolaghat',
                 'Siliguri',
                 'Uluberia',
                 'Hoogly']}

# Charger ID - Charger Type Mapping
charger_names = {
    1: "Community Bus",
    4: "Community Home",
    5: "Community Home",
    6: "Ather",
    7: "Tata Power",
    8: "EESL",
    9: "Tata",
    10: "Others",
    11: "Zeon",
    12: "Statiq",
    13: "Volttic",
    14: "Plug N Go",
    15: "BESCOM",
    16: "Electreefi",
    17: "KSEB",
    18: "Chargegrid",
    19: "Others",
    20: "FORTUM",
    21: "Others",
    22: "Others",
    23: "BPCL",
}

# Charger Type - Color Mapping
color_map = {
    "Community Bus": "red",
    "Community Home": "purple",
    "Ather": "beige",
    "Tata Power": "black",
    "EESL": "blue",
    "Tata": "darkblue",
    "Zeon": "darkgreen",
    "Statiq": "darkpurple",
    "Volttic": "lightred",
    "Plug N Go": "lightgray",
    "BESCOM": "darkred",
    "Electreefi": "pink",
    "KSEB": "lightblue",
    "Chargegrid": "gray",
    "FORTUM": "green",
    "BPCL": "orange",
    "Others": "white",
}
